- name: "Installing docker-compose on {{ ansible_distribution }}"
  include_tasks: "ubuntu.yml"
  when: 
    - ansible_distribution == "Ubuntu"

- name: "Installing docker-compose on {{ ansible_distribution }}"
  include_tasks: "alt.yml"
  when: 
    - ansible_distribution == "Altlinux"

- name: "Pip install docker-compose"
  pip: 
    name: docker-compose