- name: "Installing packages for docker on {{ ansible_distribution }}"
  apt:
    name: "{{ ubuntu_docker_packages }}"
    state: "present"
    update_cache: true

- name: "Add Docker GPG apt Key"
  apt_key:
    url: "{{ ubuntu_docker_gpg_key }}"
    state: "present"

- name: "Add Docker Repository"
  apt_repository:
    repo: "{{ ubuntu_docker_repository }}"
    state: "present"
    
- name: "Update apt and install docker-ce"
  apt:
    name: "docker-ce"
    state: "present"
    update_cache: true
    
- name: "Install Docker Module for Python"
  pip:
    name: "{{ ubuntu_pip_module_docker }}"

- name: "Started and enabled docker"
  systemd:
    name: "docker"
    state: "started"
    enabled: true